CREATE TABLE Product_Category (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE Product (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category_id INTEGER REFERENCES Product_Category(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
